<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>Assignment7</RootNamespace>
    <AssemblyName>Assignment7</AssemblyName>
    <UseUwp>true</UseUwp>
    <UseUwpTools>true</UseUwpTools>
    <EnableMsixTooling>true</EnableMsixTooling>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <DefaultLanguage>en-US</DefaultLanguage>
    <ApplicationManifest>Package.appxmanifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <SelfContained>true</SelfContained>
    <PublishAot>false</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
  </ItemGroup>
</Project>
